export const covidTill0721 = {
  "results": [{
    "locationId": 951002,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "日本",
    "countryEnglishName": "Japan",
    "countryFullName": "Japan",
    "provinceName": "日本",
    "provinceEnglishName": "Japan",
    "provinceShortName": "日本",
    "currentConfirmedCount": 5341,
    "confirmedCount": 23657,
    "suspectedCount": 0,
    "curedCount": 17331,
    "deadCount": 985,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 952009,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "新加坡",
    "countryEnglishName": "Singapore",
    "countryFullName": "Singapore",
    "provinceName": "新加坡",
    "provinceEnglishName": "Singapore",
    "provinceShortName": "新加坡",
    "currentConfirmedCount": 4814,
    "confirmedCount": 47126,
    "suspectedCount": 0,
    "curedCount": 42285,
    "deadCount": 27,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 951001,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "中国",
    "countryEnglishName": "China",
    "countryFullName": "China",
    "provinceName": "中国",
    "provinceEnglishName": "China",
    "provinceShortName": "中国",
    "currentConfirmedCount": 656,
    "confirmedCount": 85765,
    "suspectedCount": 0,
    "curedCount": 80458,
    "deadCount": 4651,
    "comment": null,
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 973003,
    "continentName": "南美洲",
    "continentEnglishName": "South America",
    "countryName": "巴西",
    "countryEnglishName": "Brazil",
    "countryFullName": "Brazil",
    "provinceName": "巴西",
    "provinceEnglishName": "Brazil",
    "provinceShortName": "巴西",
    "currentConfirmedCount": 635818,
    "confirmedCount": 1966748,
    "suspectedCount": 0,
    "curedCount": 1255564,
    "deadCount": 75366,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  },
  {
    "locationId": 961007,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "英国",
    "countryEnglishName": "United Kingdom",
    "countryFullName": "The United Kingdom",
    "provinceName": "英国",
    "provinceEnglishName": "United Kingdom",
    "provinceShortName": "英国",
    "currentConfirmedCount": 246894,
    "confirmedCount": 292552,
    "suspectedCount": 0,
    "curedCount": 539,
    "deadCount": 45119,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 964006,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "俄罗斯",
    "countryEnglishName": "Russia",
    "countryFullName": "Russian Federation",
    "provinceName": "俄罗斯",
    "provinceEnglishName": "Russia",
    "provinceShortName": "俄罗斯",
    "currentConfirmedCount": 209168,
    "confirmedCount": 752797,
    "suspectedCount": 0,
    "curedCount": 531692,
    "deadCount": 11937,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 953003,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "印度",
    "countryEnglishName": "India",
    "countryFullName": "India",
    "provinceName": "印度",
    "provinceEnglishName": "India",
    "provinceShortName": "印度",
    "currentConfirmedCount": 331146,
    "confirmedCount": 968876,
    "suspectedCount": 0,
    "curedCount": 612815,
    "deadCount": 24915,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 964007,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "乌克兰",
    "countryEnglishName": "Ukraine",
    "countryFullName": "Ukraine",
    "provinceName": "乌克兰",
    "provinceEnglishName": "Ukraine",
    "provinceShortName": "乌克兰",
    "currentConfirmedCount": 26079,
    "confirmedCount": 56455,
    "suspectedCount": 0,
    "curedCount": 28931,
    "deadCount": 1445,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 963003,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "德国",
    "countryEnglishName": "Germany",
    "countryFullName": "Germany",
    "provinceName": "德国",
    "provinceEnglishName": "Germany",
    "provinceShortName": "德国",
    "currentConfirmedCount": 4782,
    "confirmedCount": 200260,
    "suspectedCount": 0,
    "curedCount": 186400,
    "deadCount": 9078,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 982013,
    "continentName": "非洲",
    "continentEnglishName": "Africa",
    "countryName": "尼日利亚",
    "countryEnglishName": "Nigeria",
    "countryFullName": "Nigeria",
    "provinceName": "尼日利亚",
    "provinceEnglishName": "Nigeria",
    "provinceShortName": "尼日利亚",
    "currentConfirmedCount": 19500,
    "confirmedCount": 34259,
    "suspectedCount": 0,
    "curedCount": 13999,
    "deadCount": 760,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 810000,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "中国",
    "countryEnglishName": "China",
    "countryFullName": null,
    "provinceName": "香港",
    "provinceEnglishName": "Hong Kong",
    "provinceShortName": "香港",
    "currentConfirmedCount": 391,
    "confirmedCount": 1655,
    "suspectedCount": 63,
    "curedCount": 1254,
    "deadCount": 10,
    "comment": "疑似1例",
    "cities": [],
    "updateTime": 1594914617723
  }, {
    "locationId": 971002,
    "continentName": "北美洲",
    "continentEnglishName": "North America",
    "countryName": "美国",
    "countryEnglishName": "United States of America",
    "countryFullName": "United States of America",
    "provinceName": "美国",
    "provinceEnglishName": "United States of America",
    "provinceShortName": "美国",
    "currentConfirmedCount": 2286469,
    "confirmedCount": 3499771,
    "suspectedCount": 0,
    "curedCount": 1075882,
    "deadCount": 137420,
    "comment": "",
    "cities": null,
    "updateTime": 1594914617723
  }, {
    "locationId": 650000,
    "continentName": "亚洲",
    "continentEnglishName": "Asia",
    "countryName": "中国",
    "countryEnglishName": "China",
    "countryFullName": null,
    "provinceName": "新疆维吾尔自治区",
    "provinceEnglishName": "Xinjiang",
    "provinceShortName": "新疆",
    "currentConfirmedCount": 1,
    "confirmedCount": 77,
    "suspectedCount": 0,
    "curedCount": 73,
    "deadCount": 3,
    "comment": "",
    "cities": [
      {
        "cityName": "乌鲁木齐",
        "currentConfirmedCount": 1,
        "confirmedCount": 24,
        "suspectedCount": 0,
        "curedCount": 23,
        "deadCount": 0,
        "locationId": 650100,
        "cityEnglishName": "Urumqi"
      },
      {
        "cityName": "伊犁州",
        "currentConfirmedCount": 0,
        "confirmedCount": 18,
        "suspectedCount": 0,
        "curedCount": 18,
        "deadCount": 0,
        "locationId": 654000,
        "cityEnglishName": "Yili"
      },
      {
        "cityName": "兵团第四师",
        "currentConfirmedCount": 0,
        "confirmedCount": 10,
        "suspectedCount": 0,
        "curedCount": 9,
        "deadCount": 1,
        "locationId": 0,
        "cityEnglishName": "Xinjiang Production and Construction Corps 4th Division"
      },
      {
        "cityName": "兵团第八师石河子市",
        "currentConfirmedCount": 0,
        "confirmedCount": 4,
        "suspectedCount": 0,
        "curedCount": 3,
        "deadCount": 1,
        "locationId": 0,
        "cityEnglishName": "Shihezi, Xinjiang Production and Construction Corps 8th Division"
      },
      {
        "cityName": "兵团第九师",
        "currentConfirmedCount": 0,
        "confirmedCount": 4,
        "suspectedCount": 0,
        "curedCount": 3,
        "deadCount": 1,
        "locationId": 0,
        "cityEnglishName": "Xinjiang Production and Construction Corps 9th Division"
      },
      {
        "cityName": "昌吉州",
        "currentConfirmedCount": 0,
        "confirmedCount": 4,
        "suspectedCount": 0,
        "curedCount": 4,
        "deadCount": 0,
        "locationId": 0,
        "cityEnglishName": "Changji"
      },
      {
        "cityName": "吐鲁番市",
        "currentConfirmedCount": 0,
        "confirmedCount": 3,
        "suspectedCount": 0,
        "curedCount": 3,
        "deadCount": 0,
        "locationId": 650400,
        "cityEnglishName": "Turpan"
      },
      {
        "cityName": "巴州",
        "currentConfirmedCount": 0,
        "confirmedCount": 3,
        "suspectedCount": 0,
        "curedCount": 3,
        "deadCount": 0,
        "locationId": 511902,
        "cityEnglishName": "Bayingolin Mongol Autonomous Prefecture"
      },
      {
        "cityName": "兵团第十二师",
        "currentConfirmedCount": 0,
        "confirmedCount": 3,
        "suspectedCount": 0,
        "curedCount": 3,
        "deadCount": 0,
        "locationId": 0,
        "cityEnglishName": "Xinjiang Production and Construction Corps 12th Division"
      },
      {
        "cityName": "兵团第六师五家渠市",
        "currentConfirmedCount": 0,
        "confirmedCount": 2,
        "suspectedCount": 0,
        "curedCount": 2,
        "deadCount": 0,
        "locationId": 0,
        "cityEnglishName": "Wujiaqu, Xinjiang Production and Construction Corps 5th Division"
      },
      {
        "cityName": "兵团第七师",
        "currentConfirmedCount": 0,
        "confirmedCount": 1,
        "suspectedCount": 0,
        "curedCount": 1,
        "deadCount": 0,
        "locationId": 0,
        "cityEnglishName": "Xinjiang Production and Construction Corps 7th Division"
      },
      {
        "cityName": "阿克苏地区",
        "currentConfirmedCount": 0,
        "confirmedCount": 1,
        "suspectedCount": 0,
        "curedCount": 1,
        "deadCount": 0,
        "locationId": 652900,
        "cityEnglishName": "Akesu"
      }
    ],
    "updateTime": 1594883339824
  }, {
    "locationId": 990001,
    "continentName": "大洋洲",
    "continentEnglishName": "Oceania",
    "countryName": "澳大利亚",
    "countryEnglishName": "Australia",
    "countryFullName": "Australia",
    "provinceName": "澳大利亚",
    "provinceEnglishName": "Australia",
    "provinceShortName": "澳大利亚",
    "currentConfirmedCount": 2308,
    "confirmedCount": 10251,
    "suspectedCount": 0,
    "curedCount": 7835,
    "deadCount": 108,
    "comment": "",
    "cities": null,
    "updateTime": 1594881238316
  }, {
    "locationId": 965008,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "意大利",
    "countryEnglishName": "Italy",
    "countryFullName": "Italy",
    "provinceName": "意大利",
    "provinceEnglishName": "Italy",
    "provinceShortName": "意大利",
    "currentConfirmedCount": 12493,
    "confirmedCount": 243506,
    "suspectedCount": 0,
    "curedCount": 196016,
    "deadCount": 34997,
    "comment": "",
    "cities": null,
    "updateTime": 1594881238316
  }, {
    "locationId": 961002,
    "continentName": "欧洲",
    "continentEnglishName": "Europe",
    "countryName": "法国",
    "countryEnglishName": "France",
    "countryFullName": "France",
    "provinceName": "法国",
    "provinceEnglishName": "France",
    "provinceShortName": "法国",
    "currentConfirmedCount": 64364,
    "confirmedCount": 173304,
    "suspectedCount": 0,
    "curedCount": 78820,
    "deadCount": 30120,
    "comment": "",
    "cities": null,
    "updateTime": 1594881238316
  },],
  "success": true
}

